[package]
name = "datastructure"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5"


[[bin]]
name = "001"
path = "src/bin/001.rs"

[[bin]]
name = "002"
path = "src/bin/002.rs"

[[bin]]
name = "003"
path = "src/bin/003.rs"

[[bin]]
name = "004"
path = "src/bin/004.rs"

[[bin]]
name = "005"
path = "src/bin/005.rs"

[[bin]]
name = "006"
path = "src/bin/006.rs"
